name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set timestamp as an environment variable
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag nandinichatterjee/myplugin:0.1 \
          --tag nandinichatterjee/myplugin:0.2 \
          --tag nandinichatterjee/myplugin:latest \
          --tag nandinichatterjee/myplugin:${{ github.run_number }} \
          --tag nandinichatterjee/myplugin:${{ github.run_id }} \
          --tag nandinichatterjee/myplugin:${{ env.TIMESTAMP }} \
          --push .
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
