name: "[Dispatch] Daily build"

on:
  workflow_dispatch:

env:
  BRANCH: main

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      TIME: ${{ steps.get_date.outputs.TIME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Date
        id: get_date
        run: |
          sudo timedatectl set-timezone Europe/London
          CURRENT_TIME=$(date +'%Y%m%d.%H%M%S')
          
          echo "TIME=$CURRENT_TIME" >> $GITHUB_ENV
          echo "TIME=$CURRENT_TIME" >> $GITHUB_OUTPUT

      - name: Build and push to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            nandinichatterjee/${{ github.event.repository.name }}:latest
            nandinichatterjee/${{ github.event.repository.name }}:${{ env.TIME }}
          build-args: |
            PACKAGE_VERSION=${{ env.PACKAGE_VERSION }}
            BRANCH_NAME=${{ env.BRANCH_NAME }}
          provenance: false

      - name: Notice when job fails
        if: failure()
        run: echo "Job failed"
