name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      TIMESTAMP: ${{ format('{0:yyyy-MM-ddTHH-mm-ss}', github.event.head_commit.timestamp) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Create Buildx builder
      run: docker buildx create --use --name=mybuilder --platform=linux/amd64,linux/arm64

    - name: Set up QEMU (for ARM64 platforms)
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          latest
          ${{ github.sha }}
          ${{ TIMESTAMP }}
        builder: mybuilder  # Explicitly specify the builder
        platforms: linux/amd64,linux/arm64  # Multi-architecture support
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug - List builders (after build)
      run: docker buildx ls

