name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set date
        id: set-date
        run: echo "DATE_FORMAT=$(date +'%Y-%m-%d' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Debug - Verify DATE_FORMAT
        run: echo "DATE_FORMAT=${DATE_FORMAT}"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            latest
            ${{ secrets.DOCKERHUB_USERNAME }}/myplugin:${{ env.DATE_FORMAT }}
            ${{ secrets.DOCKERHUB_USERNAME }}/myplugin:latest

          platforms: linux/amd64,linux/arm64
