name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set timestamp as an environment variable
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/buildx-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        file: nandinichatterjee/myplugin  # Adjust path to your Dockerfile
        push: true
        tags: |
          0.1
          0.2
          latest
          ${{ github.run_number }}
          ${{ github.run_id }}
          ${{ env.TIMESTAMP }}

