name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker images
      run: |
        docker buildx build \
          --platform linux/amd64 \
          --tag nandinichatterjee/myplugin:0.1 \
          --push .

        docker buildx build \
          --platform linux/arm64 \
          --tag nandinichatterjee/myplugin:0.2 \
          --push .
