name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        token: ${{ secrets.GH_PAT }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get Date
      id: get_date
      run: |
        sudo ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
        CURRENT_TIME=$(date +'%Y%m%d.%H%M%S')
        
        echo "TIME=$CURRENT_TIME" >> $GITHUB_ENV
        echo "TIME=$CURRENT_TIME" >> $GITHUB_OUTPUT
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
#          nandinichatterjee/${{ github.event.repository.name }}:${{ steps.get_date.outputs.TIME }}
          myplugin:latest nandinichatterjee/myplugin:${{ steps.get_date.outputs.TIME }}
        build-args: |
          PACKAGE_VERSION=${{ env.PACKAGE_VERSION }}
          BRANCH_NAME=${{ env.BRANCH_NAME }}
        provenance: false